import React from "react";
import { getSamplePortfolio } from "./preview/samplePortfolios";
import { getInitials } from "./utils/templateHelpers";

function PreviewFrame({ children, background = "#111", foreground = "#fff" }) {
  return <div style={{ height: "100%", borderRadius: 16, overflow: "hidden", background, color: foreground, position: "relative", boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.06)" }}>{children}</div>;
}

function DevFolioMini({ portfolio }) {
  const { profile, themeData: theme } = portfolio;
  return <PreviewFrame background={theme.backgroundColor} foreground={theme.textColor}><div style={{ position: "absolute", inset: 0, backgroundImage: "linear-gradient(rgba(0,255,136,0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(0,255,136,0.08) 1px, transparent 1px)", backgroundSize: "28px 28px" }} /><div style={{ position: "relative", padding: 16, display: "grid", gridTemplateRows: "auto 1fr", height: "100%" }}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 9, letterSpacing: "0.12em", textTransform: "uppercase", opacity: 0.8 }}><span style={{ color: theme.accentColor }}>// {profile.displayName}</span><span>Work Skills Contact</span></div><div style={{ display: "grid", gridTemplateColumns: "1.1fr 0.9fr", gap: 14, alignItems: "center" }}><div><div style={{ fontSize: 8, letterSpacing: "0.24em", opacity: 0.6 }}>HELLO, I&apos;M</div><div style={{ fontSize: 24, lineHeight: 0.96, marginTop: 6, fontWeight: 700 }}>{profile.fullName.split(" ")[0]}<br />{profile.fullName.split(" ").slice(1).join(" ")}</div><div style={{ marginTop: 8, color: theme.accentColor, fontSize: 11, fontWeight: 700 }}>{profile.professionalTitle}</div></div><div style={{ background: "rgba(0,0,0,0.55)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 14, padding: 10, height: 118 }}><div style={{ display: "flex", gap: 5, marginBottom: 10 }}><span style={{ width: 7, height: 7, borderRadius: "50%", background: "#ff5f57" }} /><span style={{ width: 7, height: 7, borderRadius: "50%", background: "#febc2e" }} /><span style={{ width: 7, height: 7, borderRadius: "50%", background: "#28c840" }} /></div><div style={{ height: 82, borderRadius: 10, background: "rgba(0,255,136,0.1)", display: "grid", placeItems: "center", color: theme.accentColor, fontSize: 22, fontWeight: 700 }}>{getInitials(profile.fullName)}</div></div></div></div></PreviewFrame>;
}

function ClassicProMini({ portfolio }) {
  const { profile, themeData: theme } = portfolio;
  return <PreviewFrame background="#ffffff" foreground={theme.textColor}><div style={{ display: "grid", gridTemplateRows: "32px 1fr", height: "100%" }}><div style={{ borderBottom: "1px solid rgba(15,23,42,0.08)", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 12px", fontSize: 9 }}><strong>{profile.fullName}</strong><span style={{ color: theme.accentColor }}>{profile.email}</span></div><div style={{ display: "grid", gridTemplateColumns: "78px 1fr", gap: 10, padding: 12 }}><div style={{ border: "1px solid rgba(15,23,42,0.08)", borderRadius: 12, padding: 8 }}><div style={{ width: 34, height: 34, borderRadius: "50%", background: "#eef2f7", display: "grid", placeItems: "center", fontSize: 12, fontWeight: 700 }}>{getInitials(profile.fullName)}</div><div style={{ marginTop: 8, fontSize: 8, color: theme.accentColor, fontWeight: 700 }}>{profile.professionalTitle}</div></div><div style={{ display: "grid", gap: 7 }}>{[1,2,3].map((item) => <div key={item} style={{ border: "1px solid rgba(15,23,42,0.08)", borderRadius: 12, padding: 8 }}><div style={{ fontSize: 7, color: "#64748b", textTransform: "uppercase", letterSpacing: "0.14em" }}>Experience</div><div style={{ marginTop: 5, height: 8, borderRadius: 999, background: "#0f172a", width: `${65 - item * 8}%` }} /><div style={{ marginTop: 5, height: 6, borderRadius: 999, background: "#dbe4ef", width: `${90 - item * 10}%` }} /></div>)}</div></div></div></PreviewFrame>;
}

function DesignCaseMini({ portfolio }) {
  const { profile, themeData: theme } = portfolio;
  return <PreviewFrame background={theme.backgroundColor} foreground={theme.textColor}><div style={{ display: "grid", gridTemplateColumns: "64px 1fr", height: "100%" }}><div style={{ background: "rgba(22,17,15,0.96)", color: "#fff8f1", padding: 10, display: "grid", alignContent: "space-between" }}><div style={{ fontSize: 16, fontWeight: 800 }}>{getInitials(profile.fullName)}</div><div style={{ display: "grid", gap: 4 }}>{[1,2,3,4].map((item) => <span key={item} style={{ height: 2, width: 18 + item * 6, background: theme.accentColor, opacity: 0.9 }} />)}</div></div><div style={{ padding: 12, display: "grid", gridTemplateRows: "auto 1fr auto", gap: 10 }}><div><div style={{ fontSize: 7, letterSpacing: "0.18em", textTransform: "uppercase", color: theme.accentColor }}>Editorial Portfolio</div><div style={{ marginTop: 4, fontSize: 20, fontWeight: 800, lineHeight: 0.95 }}>{profile.fullName}</div></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}><div style={{ background: "#fffaf3", borderRadius: 12, padding: 8 }}><div style={{ fontSize: 7, textTransform: "uppercase", letterSpacing: "0.16em", color: theme.accentColor }}>Case Study</div><div style={{ marginTop: 22, height: 28, borderRadius: 8, background: "linear-gradient(135deg, rgba(255,90,54,0.18), rgba(255,255,255,0.9))" }} /></div><div style={{ background: "#1f1917", borderRadius: 12, padding: 8, color: "#fffaf3" }}><div style={{ fontSize: 7, textTransform: "uppercase", letterSpacing: "0.16em", color: theme.accentColor }}>Selected Work</div><div style={{ marginTop: 12, display: "grid", gap: 5 }}>{[1,2,3].map((item) => <span key={item} style={{ height: 6, borderRadius: 999, background: "rgba(255,255,255,0.12)" }} />)}</div></div></div><div style={{ fontSize: 7, letterSpacing: "0.14em", textTransform: "uppercase", color: "#6b5f57" }}>Projects Testimonials Contact</div></div></div></PreviewFrame>;
}

function LensWorkMini({ portfolio }) {
  const { profile, themeData: theme } = portfolio;
  return <PreviewFrame background="#060606" foreground={theme.textColor}><div style={{ height: "100%", position: "relative", overflow: "hidden" }}><div style={{ position: "absolute", inset: 0, background: "linear-gradient(135deg, rgba(232,197,71,0.12), transparent 30%, transparent 70%, rgba(232,197,71,0.18))" }} /><div style={{ position: "absolute", inset: 12, borderRadius: 16, border: "1px solid rgba(255,255,255,0.08)" }} /><div style={{ position: "relative", height: "100%", display: "grid", gridTemplateRows: "1fr auto", padding: 14 }}><div style={{ display: "grid", alignItems: "end" }}><div><div style={{ fontSize: 7, letterSpacing: "0.26em", textTransform: "uppercase", color: theme.accentColor }}>Cinematic Portfolio</div><div style={{ marginTop: 6, fontSize: 24, lineHeight: 0.9, fontWeight: 700 }}>{profile.fullName}</div></div></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 6 }}>{[1,2,3].map((item) => <div key={item} style={{ height: 46, borderRadius: 10, background: `linear-gradient(180deg, rgba(232,197,71,${0.15 + item * 0.06}), rgba(255,255,255,0.04))` }} />)}</div></div></div></PreviewFrame>;
}

function MentorHubMini({ portfolio }) {
  const { profile, themeData: theme } = portfolio;
  return <PreviewFrame background={theme.backgroundColor} foreground={theme.textColor}><div style={{ position: "absolute", width: 120, height: 120, borderRadius: "50%", top: -20, right: -10, background: "radial-gradient(circle, rgba(168,85,247,0.34), transparent 70%)" }} /><div style={{ padding: 14, display: "grid", gridTemplateRows: "auto 1fr auto", height: "100%" }}><div style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "6px 10px", borderRadius: 999, background: "rgba(255,255,255,0.08)", fontSize: 8, letterSpacing: "0.12em", textTransform: "uppercase" }}>Mentor Hub</div><div style={{ display: "grid", alignContent: "center" }}><div style={{ fontSize: 22, fontWeight: 800, lineHeight: 0.95 }}>{profile.fullName}</div><div style={{ marginTop: 8, color: theme.accentColor, fontSize: 10, fontWeight: 700 }}>{profile.professionalTitle}</div></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 6 }}>{[1,2,3].map((item) => <div key={item} style={{ height: 32, borderRadius: 12, background: "rgba(255,255,255,0.08)" }} />)}</div></div></PreviewFrame>;
}

function FreelancerKitMini({ portfolio }) {
  const { profile, themeData: theme } = portfolio;
  return <PreviewFrame background={theme.backgroundColor} foreground={theme.textColor}><div style={{ display: "grid", gridTemplateColumns: "72px 1fr", height: "100%" }}><div style={{ background: "#102033", color: "#F8FAFC", padding: 10, display: "grid", alignContent: "space-between" }}><div style={{ width: 34, height: 34, borderRadius: 12, background: "rgba(56,189,248,0.16)", display: "grid", placeItems: "center", fontWeight: 800 }}>{getInitials(profile.fullName)}</div><div style={{ display: "grid", gap: 4 }}>{[1,2,3].map((item) => <span key={item} style={{ height: 6, borderRadius: 999, background: "rgba(255,255,255,0.18)" }} />)}</div></div><div style={{ padding: 12, display: "grid", gridTemplateRows: "auto 1fr", gap: 10 }}><div><div style={{ fontSize: 7, letterSpacing: "0.16em", textTransform: "uppercase", color: theme.accentColor }}>Freelancer Kit</div><div style={{ marginTop: 4, fontSize: 19, fontWeight: 800 }}>{profile.fullName}</div></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>{[1,2].map((item) => <div key={item} style={{ borderRadius: 14, background: "#ffffff", border: "1px solid rgba(15,23,42,0.08)", padding: 8 }}><div style={{ height: 18, borderRadius: 8, background: "rgba(56,189,248,0.12)" }} /><div style={{ marginTop: 8, height: 6, borderRadius: 999, background: "#dbe4ef" }} /></div>)}</div></div></div></PreviewFrame>;
}

function StartupFounderMini({ portfolio }) {
  const { profile, themeData: theme } = portfolio;
  return <PreviewFrame background={theme.backgroundColor} foreground={theme.textColor}><div style={{ position: "absolute", inset: 0, background: "radial-gradient(circle at 80% 20%, rgba(255,107,53,0.22), transparent 28%)" }} /><div style={{ position: "relative", padding: 14, display: "grid", gridTemplateRows: "auto 1fr auto", height: "100%" }}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 8, letterSpacing: "0.16em", textTransform: "uppercase" }}><span>FounderOS</span><span style={{ color: theme.accentColor }}>Impact</span></div><div style={{ display: "grid", alignContent: "center" }}><div style={{ fontSize: 24, lineHeight: 0.9, fontWeight: 800 }}>{profile.fullName}</div><div style={{ marginTop: 10, display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 8 }}>{["12M","37%","4x"].map((metric) => <div key={metric} style={{ border: "1px solid rgba(255,255,255,0.08)", borderRadius: 12, padding: 8, textAlign: "center" }}><div style={{ color: theme.accentColor, fontSize: 10, fontWeight: 800 }}>{metric}</div></div>)}</div></div><div style={{ fontSize: 7, letterSpacing: "0.16em", textTransform: "uppercase", color: "rgba(248,243,236,0.65)" }}>Projects Experience Contact</div></div></PreviewFrame>;
}

function WritersDeskMini({ portfolio }) {
  const { profile, themeData: theme } = portfolio;
  return <PreviewFrame background={theme.backgroundColor} foreground={theme.textColor}><div style={{ display: "grid", gridTemplateRows: "10px auto 1fr", height: "100%" }}><div style={{ background: `linear-gradient(90deg, ${theme.accentColor} 0%, ${theme.accentColor} 34%, rgba(146,64,14,0.12) 34%)` }} /><div style={{ padding: "12px 14px 0" }}><div style={{ fontSize: 7, letterSpacing: "0.18em", textTransform: "uppercase", color: theme.accentColor }}>Writers Desk</div><div style={{ marginTop: 4, fontSize: 20, fontWeight: 700 }}>{profile.fullName}</div></div><div style={{ padding: 14, display: "grid", gap: 8 }}><div style={{ height: 38, borderRadius: 14, background: "rgba(146,64,14,0.08)" }} />{[1,2,3].map((item) => <div key={item} style={{ height: 10, borderRadius: 999, background: "rgba(28,25,23,0.08)", width: `${92 - item * 14}%` }} />)}</div></div></PreviewFrame>;
}

export default function TemplateCardPreview({ templateKey, template, compact = false }) {
  const portfolio = getSamplePortfolio(templateKey || template?.templateKey || template?.renderFamily);
  const key = String(templateKey || template?.templateKey || template?.renderFamily || "CLASSICPRO").toUpperCase();
  const content = {
    DEVFOLIO: <DevFolioMini portfolio={portfolio} />,
    CLASSICPRO: <ClassicProMini portfolio={portfolio} />,
    DESIGNCASE: <DesignCaseMini portfolio={portfolio} />,
    LENSWORK: <LensWorkMini portfolio={portfolio} />,
    MENTORHUB: <MentorHubMini portfolio={portfolio} />,
    FREELANCERKIT: <FreelancerKitMini portfolio={portfolio} />,
    STARTUPFOUNDER: <StartupFounderMini portfolio={portfolio} />,
    WRITERSDESK: <WritersDeskMini portfolio={portfolio} />,
  }[key] || <ClassicProMini portfolio={portfolio} />;
  return <div style={{ height: compact ? 128 : 148 }}>{content}</div>;
}
