import React, { useEffect, useMemo, useState } from "react";
import { contactAPI } from "../api/api";
import { injectThemeVars } from "./utils/templateHelpers";

const STYLE_ID = "writersdesk-template-styles";
const FONT_ID = "writersdesk-template-font";
const css = `
.writersdesk-root{background:var(--color-bg);color:var(--color-text);min-height:100vh;font-family:var(--font-main),"Playfair Display",serif}.writersdesk-root *{box-sizing:border-box}.writersdesk-bar{position:fixed;top:0;left:0;right:0;height:5px;background:rgba(146,64,14,.12);z-index:30}.writersdesk-progress{height:100%;background:var(--color-accent);transition:width .14s ease}.writersdesk-shell{max-width:980px;margin:0 auto;padding:88px 20px 48px}.writersdesk-header{display:grid;gap:12px;border-bottom:1px solid rgba(28,25,23,.08);padding-bottom:26px}.writersdesk-kicker{font-size:.78rem;letter-spacing:.22em;text-transform:uppercase;color:var(--color-accent);font-family:Inter,sans-serif}.writersdesk-title{font-size:clamp(3rem,6vw,5.4rem);line-height:.92;margin:0;color:#1c1917}.writersdesk-sub{font-size:1.18rem;color:#6b5b50}.writersdesk-grid{display:grid;grid-template-columns:1fr 280px;gap:24px;margin-top:28px}.writersdesk-article{padding-bottom:24px;margin-bottom:24px;border-bottom:1px solid rgba(28,25,23,.08)}.writersdesk-article h2{font-size:2rem;margin:0 0 10px}.writersdesk-article p{color:#5c5149;line-height:1.9}.writersdesk-meta{font-family:Inter,sans-serif;font-size:.78rem;letter-spacing:.16em;text-transform:uppercase;color:#8a786a}.writersdesk-sidebar{position:sticky;top:96px;align-self:start;padding:20px;border-radius:24px;background:#fffaf3;border:1px solid rgba(28,25,23,.08)}.writersdesk-sidebar h3{margin-top:0}.writersdesk-list{display:grid;gap:10px;color:#5c5149}.writersdesk-contact{margin-top:28px;padding:24px;border-radius:28px;background:#fffaf3;border:1px solid rgba(28,25,23,.08)}.writersdesk-contact form{display:grid;gap:12px;margin-top:18px}.writersdesk-contact input,.writersdesk-contact textarea{width:100%;padding:13px 15px;border-radius:14px;border:1px solid rgba(28,25,23,.12);background:#fff;color:#1c1917;font:inherit}.writersdesk-contact button{padding:12px 16px;border:none;border-radius:999px;background:var(--color-accent);color:#fff8f1;font-weight:800;cursor:pointer}@media (max-width:920px){.writersdesk-grid{grid-template-columns:1fr}.writersdesk-sidebar{position:static}}
`;
export default function WritersDeskTemplate({ portfolio }) {
  const profile = portfolio?.profile || {};
  const sections = portfolio?.sections || {};
  const style = injectThemeVars(portfolio?.themeData || {});
  const [progress, setProgress] = useState(0);
  useEffect(() => { if (!document.getElementById(STYLE_ID)) { const s=document.createElement("style"); s.id=STYLE_ID; s.textContent=css; document.head.appendChild(s);} if (!document.getElementById(FONT_ID)) { const l=document.createElement("link"); l.id=FONT_ID; l.rel="stylesheet"; l.href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;700;800&family=Inter:wght@400;500;700&display=swap"; document.head.appendChild(l);} const onScroll=() => { const total=document.documentElement.scrollHeight-window.innerHeight; const next= total > 0 ? (window.scrollY / total) * 100 : 0; setProgress(Math.max(0, Math.min(100, next))); }; onScroll(); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll); }, []);
  const posts = useMemo(() => sections.blogPosts || sections.publications || [], [sections.blogPosts, sections.publications]);
  const submitContact = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await contactAPI.submit({ resumeId: portfolio?.resumeId, senderName: form.get("senderName"), senderEmail: form.get("senderEmail"), senderPhone: form.get("senderPhone"), subject: form.get("subject"), message: form.get("message") }); event.currentTarget.reset(); } catch (error) { console.error(error); } };
  return <div className="writersdesk-root" style={style}><div className="writersdesk-bar"><div className="writersdesk-progress" style={{ width: `${progress}%` }} /></div><div className="writersdesk-shell"><header className="writersdesk-header"><div className="writersdesk-kicker">Editorial Portfolio</div><h1 className="writersdesk-title">{profile.fullName || "Your Name"}</h1><div className="writersdesk-sub">{profile.professionalTitle || portfolio?.title || "Writer & Editor"}</div><p style={{ maxWidth: 700, color: "#5c5149", lineHeight: 1.9, margin: 0 }}>{profile.bio || "A calm, publication-first portfolio built for writers, editors, researchers, and anyone whose work deserves room to breathe."}</p></header><div className="writersdesk-grid"><main>{posts.map((post, index) => <article className="writersdesk-article" key={post.id || index}><div className="writersdesk-meta">{post.publicationName || post.publisher || "Featured Writing"}</div><h2>{post.title}</h2><p>{post.excerpt || post.description || "A polished editorial surface for long-form thoughts, publication proof, and thoughtful professional storytelling."}</p></article>)}</main><aside className="writersdesk-sidebar"><h3>About</h3><div className="writersdesk-list"><div>{profile.email}</div><div>{profile.location}</div>{(sections.skills || []).map((skill, index) => <span key={skill.id || index}>{skill.skillName || skill.name}</span>)}</div></aside></div><section className="writersdesk-contact"><div className="writersdesk-kicker">Contact</div><h2 style={{ fontSize: "2rem", margin: "8px 0 0" }}>Open to commissions, editing, and publication work.</h2><form onSubmit={submitContact}><input name="senderName" placeholder="Your name" required /><input name="senderEmail" type="email" placeholder="Your email" required /><input name="senderPhone" placeholder="Phone number" /><input name="subject" placeholder="Subject" required /><textarea name="message" rows="5" placeholder="Tell me about the piece or project" required /><button type="submit">Send message</button></form></section></div></div>;
}

